- id: '1526693224221'
  alias: Office Scenes
  trigger:
  - entity_id: input_select.office_scene
    platform: state
  condition: []
  action:
  - service: hue.hue_activate_scene
    data_template:
      group_name: Office
      scene_name: '{{ states.input_select.office_scene.state }}'
- id: '1530153580596'
  alias: Living Room Scenes
  trigger:
  - entity_id: input_select.lr_scene
    platform: state
  condition: []
  action:
  - service: hue.hue_activate_scene
    data_template:
      group_name: Living Room
      scene_name: '{{ states.input_select.living_room_scene.state }}'
