# Change the scene at sunset
  - id: anystring
    alias: "Sunset Lighting"
    trigger:
    - platform: time
      at: '19:00:00'
    condition:
    - condition: state
      entity_id: 'group.office_lights'
      state: 'on'
    action:
      - service: hue.hue_activate_scene
        data:
          group_name: "Office"
          scene_name: "Read"
# Change the scene at sunset
  - id: anyotherstring
    alias: "Sunrise Lighting"
    trigger:
    - platform: time
      at: '06:00:00'
    condition:
    - condition: state
      entity_id: 'group.office_lights'
      state: 'on'
    action:
      - service: hue.hue_activate_scene
        data:
          group_name: "Office"
          scene_name: "Concentrate"
