- id: officesunset
  alias: Sunset Lighting - Office
  trigger:
  - at: '20:30:00'
    platform: time
  condition:
  - condition: state
    entity_id: light.hue_color_lamp_4
    state: 'on'
  action:
  - data:
      group_name: Office
      scene_name: Read
    service: hue.hue_activate_scene
- id: officesunrise
  alias: Sunrise Lighting - Office
  trigger:
  - at: 08:00:00
    platform: time
  condition:
  - condition: state
    entity_id: light.hue_color_lamp_4
    state: 'on'
  action:
  - data:
      group_name: Office
      scene_name: Concentrate
    service: hue.hue_activate_scene
