homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

frontend:
config:
http:
history:
logbook:
cloud: !include clouds.yaml

# panel_custom:
#   -name:
#     title: Upcoming Events
#     icon: mdi:calendar
#     url: http://192.168.1.32:3218

switch:
  - platform: tplink
    name: String Lights
    host: !secret kasa_ip
    enable_leds: true

weather: !include weather.yaml

google:
  client_id: !secret google_id
  client_secret: !secret google_secret

neato:
  username: !secret neato_user
  password: !secret neato_pass

hue:
  bridges:
    - host: !secret hue_ip

media_player:
  - platform: cast
    host: !secret cast_ip

notify:
  - name: test
    platform: pushbullet
    api_key: !secret pushbullet_api

sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
camera: !include cameras.yaml
