homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes
config:
http:
history:
sun:
logbook:
cloud: !include clouds.yaml

input_select:
  office_scene:
    name: Scene
    options:
      - Daytime
      - Evening
    initial: 'Daytime'
    icon: mdi:palette
    
switch:
  - platform: tplink
    name: String Lights
    host: !secret kasa_ip
    enable_leds: true

google:
  client_id: !secret google_id
  client_secret: !secret google_secret

neato:
  username: !secret neato_user
  password: !secret neato_pass

device_tracker:
  - platform: netgear
    host: !secret router_ip
    username: !secret router_user
    password: !secret router_pass

# hue:
#   bridges:
#     - host: !secret hue_ip
#       allow_unreachable: true
#       allow_hue_groups: true

# cast:
#   media_player:
#   - host: !secret cast_ip

notify:
  - name: test
    platform: pushbullet
    api_key: !secret pushbullet_api

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
camera: !include cameras.yaml
