title: Home
views:
  - icon: mdi:home-assistant
    id: home
    # Name of the view. Will be used as the tooltip for tab icon
    title: Home
    theme: dark-mode
    cards:
      - type: entity-filter
        entities:
          - device_tracker.galaxys9
          - device_tracker.samsungsmg930v
        state_filter:
          - 'home'
        card:
          type: glance
          title: Home
      - type: entities
        title: Entity card
        entities:
          - light.alex
          - binary_sensor.downstairs_thermostat_has_leaf
      - type: picture-entity
        entity: camera.morty_cleaning_map
      - type: glance
        entities:
          - binary_sensor.downstairs_thermostat_online
          - calendar.malloryquaintancegmailcom
      - type: media-control
        entity: media_player.tv
  - icon: mdi:lightbulb
    id: lights
    title: Lights
    theme: dark-mode
    cards:
      - type: entities
        title: Living Room Lights
        entities:
          - group.living_room_lights
