title: Home
views:
  - icon: mdi:home-assistant
    id: home
    # Name of the view. Will be used as the tooltip for tab icon
    title: Home
    cards:
      - type: entities
        title: Entity card
        entities:
          - light.alex
          - binary_sensor.downstairs_thermostat_has_leaf
      - type: camera-preview
        entity: camera.morty_cleaning_map
      - type: glance
        entities:
          - binary_sensor.downstairs_thermostat_online
          - calendar.malloryquaintancegmailcom
      - type: media-control
        entity: media_player.tv
