title: Home
views:
  - icon: mdi:home-assistant
    id: home
    # Name of the view. Will be used as the tooltip for tab icon
    title: Home
    cards:
      - type: entities
        entities:
          - light.alex
