- platform: darksky
  api_key: !secret darksky_api
  units: us
  name: Weather
  update_interval: 300
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - daily_summary
