- platform: darksky
  api_key: !secret darksky_api
  units: us
  name: Weather
  update_interval: 300
  forecast:
    - 1
    - 2
    - 3
    - 4
    - 5
  monitored_conditions:
    - summary
    - temperature
    - temperature_min
    - temperature_max
    - humidity
    - precip_probability
    - daily_summary
    - icon
